SAVE_ATTR: ['filename','lineno','module','msg','levelname']
LOGLEVEL_ALLOWED: ['INFO','ERROR','DEBUG','WARNING']
MONGO_CONFIG: 
  host: '192.168.1.36'
  port: 27017
  username: 'admin'
  password: '123456'
